### ISSUE TITLE
user login should be implemented

### ISSUE THREAD

**Issue by oguzy** [oguzy/ovizart#4]
The uploaded data is saved according to the user_id, better to define a user and a login screen

**Comment by ncollery** [comment]
Good idea. Just don't implement unsalted sha1 hashing when you store the password ;)
You may want to ask for user name (anithing), user id (valid email) and password. store only hash of user id and pass. 

Nicolas

**Comment by oguzy** [comment]
Passwords are salted and user email is kept as it hash value. Users should be created manually, for now. A script is defined for this issue.

**Comment by ncollery** [comment]
Wonderful! Thanks.

**Comment by ncollery** [comment]
http://blog.mozilla.org/webdev/2012/06/08/lets-talk-about-password-storage/
--> 
django-sha2. :  https://github.com/fwenzel/django-sha2
